# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f539fc7d5c78cfbc61a940cda47bdbf139bd1bde1cfb099a754937e145e626993f3a299530998960673a985ecfc3f92da43315f63b7487feeaeba5897224d72f

test:
  secret_key_base: 406ff7447f69fb9e9926cb63a039fb033e80cdc46db8c4be35e10376e426ca166cd19eaaa1f48b0fe8df7cd97e9784b4ddb3a1f35af489e6dc41b874ec9f0f87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
